### ISSUE TITLE
XPCS at APS 8-ID-I Phase 1

### ISSUE THREAD

**Issue by dylanmcreynolds** [lightsources/project-management#59]
* [x] [software stack installed](https://github.com/BCDA-APS/APSshare-anaconda-issues/issues/5)
* [x] [data management workflow](https://github.com/aps-8id-trr/ipython-8idiuser/issues/39)
* [x] [instrument ready for initial operations in APS cycle 2019-3](https://github.com/aps-8id-trr/ipython-8idiuser/milestone/3)
* [ ] [use bluesky, *et al.*, for at least one user ](https://github.com/aps-8id-trr/ipython-8idiuser/issues/46)

**Comment by prjemian** [comment]
As noted in https://github.com/aps-8id-trr/ipython-8idiuser/issues/39#issuecomment-533638391, we've already tested the DM workflow from bluesky and then from the linux command line (with the tool that SPEC will use from now on). We need confirmation tests from both SPEC and bluesky that both are ready to use the APS Data Management tools with our final edit of the shared tools to initiate that workflow.

**Comment by prjemian** [comment]
The instrument works with bluesky now, we'll see what additional bluesky capabilities must be available for initial operations.   For operations with a user, we'll need some more support plans (converted from SPEC macros).

**Comment by prjemian** [comment]
Instrument is ready for operations with the new Rigaku detector.  The lambda has [one outstanding issue](https://github.com/aps-8id-trr/ipython-8idiuser/issues/74) that blocks us using it.  We're working on that now.

**Comment by prjemian** [comment]
Also, APS had a brief, unexpected shutdown this week.  We just have beam restored today.

![Clipboard01](https://user-images.githubusercontent.com/2279984/66671288-42c82680-ec21-11e9-8447-787449d88927.jpg)

**Comment by prjemian** [comment]
Also, one payoff from the bluesky effort is that the data management workflow tools can also be called from SPEC more efficiently using part of the bluesky code base.  The instrument is *very* happy about that!

I'll tick off the third checkbox, that instrument is ready for operations.

**Comment by ahexemer** [comment]
Hi 
Our lab entire is still closed due to PG&E shutting down power. 
Cheers,
Alex

**Comment by prjemian** [comment]
On the Phase 1 goals for the software stack, there is an item marked *Allow for data reduction and analysis using Xi-CAM* and this will be a challenge for us to reach since we have not yet begun to use Xi-CAM for our workflow.

**Comment by prjemian** [comment]
We worked around the [Lambda detector issue previously described](https://github.com/lightsources/project-management/issues/59#issuecomment-541150349) and have assembled all the parts for a one-day operation test 2019-11-23..  On track for Phase 1 milestone.

**Comment by dylanmcreynolds** [comment]
@prjemian @qzhang234  It seems to me that we have accomplished this task, yes?

**Comment by prjemian** [comment]
Issue #46 is still open

**Comment by qzhang234** [comment]
@prjemian @dylanmcreynolds Issue #46 has been solved with Andi's document to the Data Pilot report. The related problem now is building the Nexus format for XPCS results so I'll regard #46 itself as complete

**Comment by qzhang234** [comment]
@prjemian @dylanmcreynolds However currently we are having trouble with running Bluesky & Lambda for more than a few hours. We tried running users with Bluesky and user reported this problem. More details in the issue below:
https://github.com/aps-8id-dys/ipython-8idiuser/issues/146
I believe once this problem is solved we will try deploy Bluesky to the general users

**Comment by dylanmcreynolds** [comment]
@prjemian Good point, collecting ontology for xpcs is an on-going thing. I re-opened 46 and assigned it to relevant parties. The question I have is whether this blocks "completion" of epics Phase 1 at 8-ID-I, CSX and COSMIC.

**Comment by prjemian** [comment]
I'm not convinced that the ontology agreement should block Phase I.  A great Phase I outcome is that we have identified such and are working on it (a Phase II goal).

#### short version

We have not yet satisfied the *one-week usage* milestone.

#### long version

As for our Lambda detector, only the recent [problem](https://github.com/lightsources/project-management/issues/59#issuecomment-584288451) blocks us from completing the *one-week usage* milestone.  The problem definitely is from how we use the Lambda's EPICS support from bluesky.  New EPICS support is imminent (within the week) and that will mean replacement of existing bluesky/ophyd code.  So, we have suspended diagnosing further on the existing ophyd support layer.  As we code up the ophyd interface to the new EPICS support, we'll be watchful for exactly this problem.
